# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9419dc7ff8a7ee4e90fec0c2064e3d996eb07e3b59312702bd43fd49953e9b50e07366f9c81fd0b338c0021cd6bbaa9ad2ef751e772ed850650ac30dddde004d

test:
  secret_key_base: bd2e0c77d888bfe5507a49e51af9ba79e17bf5f29ec598a13ca4cc55f40c30c3edfd9350383ac92dabb95dd0330297526436d8fe2502b753dd130a043efba4e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
